apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonappdeployment
spec:
  revisionHistoryLimit: 10
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      name: pythonapppod
      labels:
        app: pythonapp
    spec:
      containers:
        - name:  pythonapp
          image: kohlihub/python:1
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 300m
              memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pythonappsvc
spec:
  selector:
    app: pythonapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
